# -*- coding: utf-8 -*-
"""
Created on Tue Feb 20 05:28:06 2018

@author: btb_t
"""

print("--Maximum Aerodynamic Loads on 4-Axis Probe Holder--")
print("----Forces in Newtons & Moments in Newton Meters----")            

print()
print("--Maximum Force--")
print("Dmax = ", Dmax)
print("M_Dmax = ", M_Dmax)
print("alpha_Dmax = ", np.rad2deg(alpha_Dmax))
print("beta_Dmax = ", np.rad2deg(beta_Dmax))
print("gamma_Dmax = ", np.rad2deg(gamma_Dmax))

print()
print("--Maximum Moment--")
print("Mmax = ", Mmax)
print("D_Mmax = ", D_Mmax)
print("alpha_Mmax = ", np.rad2deg(alpha_Mmax))
print("beta_Mmax = ", np.rad2deg(beta_Mmax))
print("gamma_Mmax = ", np.rad2deg(gamma_Mmax))

print()
print("--Maximum X Force--")
print("DXmax = ", DXmax)
print("D_DXmax = ", D_DXmax)
print("M_DXmax = ", M_DXmax)
print("alpha_DXmax = ", np.rad2deg(alpha_DXmax))
print("beta_DXmax = ", np.rad2deg(beta_DXmax))
print("gamma_DXmax = ", np.rad2deg(gamma_DXmax))

print()
print("--Maximum Y Force--")
print("DYmax = ", DYmax)
print("D_DYmax = ", D_DYmax)
print("M_DYmax = ", M_DYmax)
print("alpha_DYmax = ", np.rad2deg(alpha_DYmax))
print("beta_DYmax = ", np.rad2deg(beta_DYmax))
print("gamma_DYmax = ", np.rad2deg(gamma_DYmax))

print()
print("--Maximum Z Force--")
print("DZmax = ", DZmax)
print("D_DZmax = ", D_DZmax)
print("M_DZmax = ", M_DZmax)
print("alpha_DZmax = ", np.rad2deg(alpha_DZmax))
print("beta_DZmax = ", np.rad2deg(beta_DZmax))
print("gamma_DZmax = ", np.rad2deg(gamma_DZmax))

print()
print("--Minimum X Force--")
print("DXmin = ", DXmin)
print("D_DXmin = ", D_DXmin)
print("M_DXmin = ", M_DXmin)
print("alpha_DXmin = ", np.rad2deg(alpha_DXmin))
print("beta_DXmin = ", np.rad2deg(beta_DXmin))
print("gamma_DXmin = ", np.rad2deg(gamma_DXmin))

print()
print("--Minimum Y Force--")
print("DYmin = ", DYmin)
print("D_DYmin = ", D_DYmin)
print("M_DYmin = ", M_DYmin)
print("alpha_DYmin = ", np.rad2deg(alpha_DYmin))
print("beta_DYmin = ", np.rad2deg(beta_DYmin))
print("gamma_DYmin = ", np.rad2deg(gamma_DYmin))

print()
print("--Minimum Z Force--")
print("DZmin = ", DZmin)
print("D_DZmin = ", D_DZmin)
print("M_DZmin = ", M_DZmin)
print("alpha_DZmin = ", np.rad2deg(alpha_DZmin))
print("beta_DZmin = ", np.rad2deg(beta_DZmin))
print("gamma_DZmin = ", np.rad2deg(gamma_DZmin))

print()
print("--Maximum X Moment--")
print("MXmax = ", MXmax)
print("D_MXmax = ", D_MXmax)
print("M_MXmax = ", M_MXmax)
print("alpha_MXmax = ", np.rad2deg(alpha_MXmax))
print("beta_MXmax = ", np.rad2deg(beta_MXmax))
print("gamma_MXmax = ", np.rad2deg(gamma_MXmax))

print()
print("--Maximum Y Moment--")
print("MYmax = ", MYmax)
print("D_MYmax = ", D_MYmax)
print("M_MYmax = ", M_MYmax)
print("alpha_MYmax = ", np.rad2deg(alpha_MYmax))
print("beta_MYmax = ", np.rad2deg(beta_MYmax))
print("gamma_MYmax = ", np.rad2deg(gamma_MYmax))

print()
print("--Maximum Z Moment--")
print("MZmax = ", MZmax)
print("D_MZmax = ", D_MZmax)
print("M_MZmax = ", M_MZmax)
print("alpha_MZmax = ", np.rad2deg(alpha_MZmax))
print("beta_MZmax = ", np.rad2deg(beta_MZmax))
print("gamma_MZmax = ", np.rad2deg(gamma_MZmax))

print()
print("--Minimum X Moment--")
print("MXmin = ", MXmin)
print("D_MXmin = ", D_MXmin)
print("M_MXmin = ", M_MXmin)
print("alpha_MXmin = ", np.rad2deg(alpha_MXmin))
print("beta_MXmin = ", np.rad2deg(beta_MXmin))
print("gamma_MXmin = ", np.rad2deg(gamma_MXmin))

print()
print("--Minimum Y Moment--")
print("MYmin = ", MYmin)
print("D_MYmin = ", D_MYmin)
print("M_MYmin = ", M_MYmin)
print("alpha_MYmin = ", np.rad2deg(alpha_MYmin))
print("beta_MYmin = ", np.rad2deg(beta_MYmin))
print("gamma_MYmin = ", np.rad2deg(gamma_MYmin))

print()
print("--Minimum Z Moment--")
print("MZmin = ", MZmin)
print("D_MZmin = ", D_MZmin)
print("M_MZmin = ", M_MZmin)
print("alpha_MZmin = ", np.rad2deg(alpha_MZmin))
print("beta_MZmin = ", np.rad2deg(beta_MZmin))
print("gamma_MZmin = ", np.rad2deg(gamma_MZmin))